apiVersion: live-streaming-server.net/v1
kind: Fleet
metadata:
  name: live-streaming-server-net-fleet
  namespace: live-streaming-server-net
spec:
  minReplicas: 1
  maxReplicas: 10

  podStreamsLimit: 2
  targetUtilization: 0.5
  
  syncPeriodSeconds: 5
  scaleUpStabilizationWindowSeconds: 0
  scaleDownStabilizationWindowSeconds: 30
  
  template:
    apiVersion: v1
    kind: Pod
    metadata:
      name: live-streaming-server-pod
      labels:
        app: live-streaming-server
    spec:
      containers:
      - name: live-streaming-server
        image: IMAGE
        imagePullPolicy: Never
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 200Mi
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort:  80
          name:  http
        - containerPort: 1935
          name: rtmp
      restartPolicy: OnFailure
      serviceAccountName: service-account