apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./fleet.yaml
- ./role.yaml
- ./role-binding.yaml
- ./service-account.yaml
- ./service.yaml
images:
- name: IMAGE
  newName: live-streaming-server-net-demo
namespace: live-streaming-server-net
