namespace: live-streaming-server-net-system
namePrefix: live-streaming-server-net-
commonLabels:
  operator: live-streaming-server-net
resources:
- operator-role.yaml
- operator-role-binding.yaml
- deployment.yaml
- fleets_live-streaming-server_net.yaml
- namespace.yaml
images:
- name: operator
  newName: accessible-docker-image
  newTag: latest
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization