image:
  tag: 7.0.10-debian-11-r1

architecture: standalone
master:
  persistence:
    enabled: false
auth:
  enabled: false
replica: 
  replicaCount: 0
resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
readinessProbe:
  initialDelaySeconds: 30