apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusters.live-streaming-server.net
spec:
  group: live-streaming-server.net
  names:
    kind: Cluster
    listKind: ClusterList
    plural: clusters
    singular: cluster
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          status:
            nullable: false
            properties: {}
            type: object
          spec:
            nullable: false
            properties:
              minReplicas:
                format: int32
                nullable: false
                type: integer
              maxReplicas:
                format: int32
                nullable: false
                type: integer
              targetUtilization:
                format: float
                nullable: false
                type: number
              podSpec:
                nullable: false
                properties:
                  streamsLimit:
                    format: int32
                    nullable: false
                    type: integer
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}