### YamlMime:ManagedReference
items:
- uid: LiveStreamingServerNet.Transmuxer.GoogleCloudStorage.Configurations
  commentId: N:LiveStreamingServerNet.Transmuxer.GoogleCloudStorage.Configurations
  id: LiveStreamingServerNet.Transmuxer.GoogleCloudStorage.Configurations
  children:
  - LiveStreamingServerNet.Transmuxer.GoogleCloudStorage.Configurations.HlsGoogleCloudStorageConfiguration
  langs:
  - csharp
  - vb
  name: LiveStreamingServerNet.Transmuxer.GoogleCloudStorage.Configurations
  nameWithType: LiveStreamingServerNet.Transmuxer.GoogleCloudStorage.Configurations
  fullName: LiveStreamingServerNet.Transmuxer.GoogleCloudStorage.Configurations
  type: Namespace
  assemblies:
  - LiveStreamingServerNet.Transmuxer.GoogleCloudStorage
references:
- uid: LiveStreamingServerNet.Transmuxer.GoogleCloudStorage.Configurations.HlsGoogleCloudStorageConfiguration
  commentId: T:LiveStreamingServerNet.Transmuxer.GoogleCloudStorage.Configurations.HlsGoogleCloudStorageConfiguration
  href: LiveStreamingServerNet.Transmuxer.GoogleCloudStorage.Configurations.HlsGoogleCloudStorageConfiguration.html
  name: HlsGoogleCloudStorageConfiguration
  nameWithType: HlsGoogleCloudStorageConfiguration
  fullName: LiveStreamingServerNet.Transmuxer.GoogleCloudStorage.Configurations.HlsGoogleCloudStorageConfiguration
