### YamlMime:ManagedReference
items:
- uid: LiveStreamingServerNet.KubernetesPod.Redis.Configurations.RedisStoreConfiguration
  commentId: T:LiveStreamingServerNet.KubernetesPod.Redis.Configurations.RedisStoreConfiguration
  id: RedisStoreConfiguration
  parent: LiveStreamingServerNet.KubernetesPod.Redis.Configurations
  children:
  - LiveStreamingServerNet.KubernetesPod.Redis.Configurations.RedisStoreConfiguration.StreamKeyPrefix
  langs:
  - csharp
  - vb
  name: RedisStoreConfiguration
  nameWithType: RedisStoreConfiguration
  fullName: LiveStreamingServerNet.KubernetesPod.Redis.Configurations.RedisStoreConfiguration
  type: Class
  source:
    remote:
      path: src/LiveStreamingServerNet.KubernetesPod.Redis/Configurations/RedisStoreConfiguration.cs
      branch: features/docs
      repo: https://josephnhtam@github.com/josephnhtam/live-streaming-server-net.git
    id: RedisStoreConfiguration
    path: ../src/LiveStreamingServerNet.KubernetesPod.Redis/Configurations/RedisStoreConfiguration.cs
    startLine: 2
  assemblies:
  - LiveStreamingServerNet.KubernetesPod.Redis
  namespace: LiveStreamingServerNet.KubernetesPod.Redis.Configurations
  syntax:
    content: public class RedisStoreConfiguration
    content.vb: Public Class RedisStoreConfiguration
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  extensionMethods:
  - System.Object.LiveStreamingServerNet.Utilities.Extensions.LockExtensions.Lock(System.Action)
- uid: LiveStreamingServerNet.KubernetesPod.Redis.Configurations.RedisStoreConfiguration.StreamKeyPrefix
  commentId: P:LiveStreamingServerNet.KubernetesPod.Redis.Configurations.RedisStoreConfiguration.StreamKeyPrefix
  id: StreamKeyPrefix
  parent: LiveStreamingServerNet.KubernetesPod.Redis.Configurations.RedisStoreConfiguration
  langs:
  - csharp
  - vb
  name: StreamKeyPrefix
  nameWithType: RedisStoreConfiguration.StreamKeyPrefix
  fullName: LiveStreamingServerNet.KubernetesPod.Redis.Configurations.RedisStoreConfiguration.StreamKeyPrefix
  type: Property
  source:
    remote:
      path: src/LiveStreamingServerNet.KubernetesPod.Redis/Configurations/RedisStoreConfiguration.cs
      branch: features/docs
      repo: https://josephnhtam@github.com/josephnhtam/live-streaming-server-net.git
    id: StreamKeyPrefix
    path: ../src/LiveStreamingServerNet.KubernetesPod.Redis/Configurations/RedisStoreConfiguration.cs
    startLine: 4
  assemblies:
  - LiveStreamingServerNet.KubernetesPod.Redis
  namespace: LiveStreamingServerNet.KubernetesPod.Redis.Configurations
  syntax:
    content: public string StreamKeyPrefix { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property StreamKeyPrefix As String
  overload: LiveStreamingServerNet.KubernetesPod.Redis.Configurations.RedisStoreConfiguration.StreamKeyPrefix*
references:
- uid: LiveStreamingServerNet.KubernetesPod.Redis.Configurations
  commentId: N:LiveStreamingServerNet.KubernetesPod.Redis.Configurations
  href: LiveStreamingServerNet.html
  name: LiveStreamingServerNet.KubernetesPod.Redis.Configurations
  nameWithType: LiveStreamingServerNet.KubernetesPod.Redis.Configurations
  fullName: LiveStreamingServerNet.KubernetesPod.Redis.Configurations
  spec.csharp:
  - uid: LiveStreamingServerNet
    name: LiveStreamingServerNet
    href: LiveStreamingServerNet.html
  - name: .
  - uid: LiveStreamingServerNet.KubernetesPod
    name: KubernetesPod
    href: LiveStreamingServerNet.KubernetesPod.html
  - name: .
  - uid: LiveStreamingServerNet.KubernetesPod.Redis
    name: Redis
    href: LiveStreamingServerNet.KubernetesPod.Redis.html
  - name: .
  - uid: LiveStreamingServerNet.KubernetesPod.Redis.Configurations
    name: Configurations
    href: LiveStreamingServerNet.KubernetesPod.Redis.Configurations.html
  spec.vb:
  - uid: LiveStreamingServerNet
    name: LiveStreamingServerNet
    href: LiveStreamingServerNet.html
  - name: .
  - uid: LiveStreamingServerNet.KubernetesPod
    name: KubernetesPod
    href: LiveStreamingServerNet.KubernetesPod.html
  - name: .
  - uid: LiveStreamingServerNet.KubernetesPod.Redis
    name: Redis
    href: LiveStreamingServerNet.KubernetesPod.Redis.html
  - name: .
  - uid: LiveStreamingServerNet.KubernetesPod.Redis.Configurations
    name: Configurations
    href: LiveStreamingServerNet.KubernetesPod.Redis.Configurations.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System.Object.LiveStreamingServerNet.Utilities.Extensions.LockExtensions.Lock(System.Action)
  commentId: M:LiveStreamingServerNet.Utilities.Extensions.LockExtensions.Lock(System.Object,System.Action)
  parent: LiveStreamingServerNet.Utilities.Extensions.LockExtensions
  definition: LiveStreamingServerNet.Utilities.Extensions.LockExtensions.Lock(System.Object,System.Action)
  href: LiveStreamingServerNet.Utilities.Extensions.LockExtensions.html#LiveStreamingServerNet_Utilities_Extensions_LockExtensions_Lock_System_Object_System_Action_
  name: Lock(object, Action)
  nameWithType: LockExtensions.Lock(object, Action)
  fullName: LiveStreamingServerNet.Utilities.Extensions.LockExtensions.Lock(object, System.Action)
  nameWithType.vb: LockExtensions.Lock(Object, Action)
  fullName.vb: LiveStreamingServerNet.Utilities.Extensions.LockExtensions.Lock(Object, System.Action)
  name.vb: Lock(Object, Action)
  spec.csharp:
  - uid: LiveStreamingServerNet.Utilities.Extensions.LockExtensions.Lock(System.Object,System.Action)
    name: Lock
    href: LiveStreamingServerNet.Utilities.Extensions.LockExtensions.html#LiveStreamingServerNet_Utilities_Extensions_LockExtensions_Lock_System_Object_System_Action_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Action
    name: Action
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.action
  - name: )
  spec.vb:
  - uid: LiveStreamingServerNet.Utilities.Extensions.LockExtensions.Lock(System.Object,System.Action)
    name: Lock
    href: LiveStreamingServerNet.Utilities.Extensions.LockExtensions.html#LiveStreamingServerNet_Utilities_Extensions_LockExtensions_Lock_System_Object_System_Action_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Action
    name: Action
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.action
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: LiveStreamingServerNet.Utilities.Extensions.LockExtensions.Lock(System.Object,System.Action)
  commentId: M:LiveStreamingServerNet.Utilities.Extensions.LockExtensions.Lock(System.Object,System.Action)
  isExternal: true
  href: LiveStreamingServerNet.Utilities.Extensions.LockExtensions.html#LiveStreamingServerNet_Utilities_Extensions_LockExtensions_Lock_System_Object_System_Action_
  name: Lock(object, Action)
  nameWithType: LockExtensions.Lock(object, Action)
  fullName: LiveStreamingServerNet.Utilities.Extensions.LockExtensions.Lock(object, System.Action)
  nameWithType.vb: LockExtensions.Lock(Object, Action)
  fullName.vb: LiveStreamingServerNet.Utilities.Extensions.LockExtensions.Lock(Object, System.Action)
  name.vb: Lock(Object, Action)
  spec.csharp:
  - uid: LiveStreamingServerNet.Utilities.Extensions.LockExtensions.Lock(System.Object,System.Action)
    name: Lock
    href: LiveStreamingServerNet.Utilities.Extensions.LockExtensions.html#LiveStreamingServerNet_Utilities_Extensions_LockExtensions_Lock_System_Object_System_Action_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Action
    name: Action
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.action
  - name: )
  spec.vb:
  - uid: LiveStreamingServerNet.Utilities.Extensions.LockExtensions.Lock(System.Object,System.Action)
    name: Lock
    href: LiveStreamingServerNet.Utilities.Extensions.LockExtensions.html#LiveStreamingServerNet_Utilities_Extensions_LockExtensions_Lock_System_Object_System_Action_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Action
    name: Action
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.action
  - name: )
- uid: LiveStreamingServerNet.Utilities.Extensions.LockExtensions
  commentId: T:LiveStreamingServerNet.Utilities.Extensions.LockExtensions
  parent: LiveStreamingServerNet.Utilities.Extensions
  href: LiveStreamingServerNet.Utilities.Extensions.LockExtensions.html
  name: LockExtensions
  nameWithType: LockExtensions
  fullName: LiveStreamingServerNet.Utilities.Extensions.LockExtensions
- uid: LiveStreamingServerNet.Utilities.Extensions
  commentId: N:LiveStreamingServerNet.Utilities.Extensions
  href: LiveStreamingServerNet.html
  name: LiveStreamingServerNet.Utilities.Extensions
  nameWithType: LiveStreamingServerNet.Utilities.Extensions
  fullName: LiveStreamingServerNet.Utilities.Extensions
  spec.csharp:
  - uid: LiveStreamingServerNet
    name: LiveStreamingServerNet
    href: LiveStreamingServerNet.html
  - name: .
  - uid: LiveStreamingServerNet.Utilities
    name: Utilities
    href: LiveStreamingServerNet.Utilities.html
  - name: .
  - uid: LiveStreamingServerNet.Utilities.Extensions
    name: Extensions
    href: LiveStreamingServerNet.Utilities.Extensions.html
  spec.vb:
  - uid: LiveStreamingServerNet
    name: LiveStreamingServerNet
    href: LiveStreamingServerNet.html
  - name: .
  - uid: LiveStreamingServerNet.Utilities
    name: Utilities
    href: LiveStreamingServerNet.Utilities.html
  - name: .
  - uid: LiveStreamingServerNet.Utilities.Extensions
    name: Extensions
    href: LiveStreamingServerNet.Utilities.Extensions.html
- uid: LiveStreamingServerNet.KubernetesPod.Redis.Configurations.RedisStoreConfiguration.StreamKeyPrefix*
  commentId: Overload:LiveStreamingServerNet.KubernetesPod.Redis.Configurations.RedisStoreConfiguration.StreamKeyPrefix
  href: LiveStreamingServerNet.KubernetesPod.Redis.Configurations.RedisStoreConfiguration.html#LiveStreamingServerNet_KubernetesPod_Redis_Configurations_RedisStoreConfiguration_StreamKeyPrefix
  name: StreamKeyPrefix
  nameWithType: RedisStoreConfiguration.StreamKeyPrefix
  fullName: LiveStreamingServerNet.KubernetesPod.Redis.Configurations.RedisStoreConfiguration.StreamKeyPrefix
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
