### YamlMime:ManagedReference
items:
- uid: LiveStreamingServerNet.Transmuxer.Configurations.FFmpegOutputPathResolverDelegate
  commentId: T:LiveStreamingServerNet.Transmuxer.Configurations.FFmpegOutputPathResolverDelegate
  id: FFmpegOutputPathResolverDelegate
  parent: LiveStreamingServerNet.Transmuxer.Configurations
  children: []
  langs:
  - csharp
  - vb
  name: FFmpegOutputPathResolverDelegate
  nameWithType: FFmpegOutputPathResolverDelegate
  fullName: LiveStreamingServerNet.Transmuxer.Configurations.FFmpegOutputPathResolverDelegate
  type: Delegate
  source:
    remote:
      path: src/LiveStreamingServerNet.Transmuxer/Configurations/FFmpegTransmuxerFactoryConfiguration.cs
      branch: features/docs
      repo: https://josephnhtam@github.com/josephnhtam/live-streaming-server-net.git
    id: FFmpegOutputPathResolverDelegate
    path: ../src/LiveStreamingServerNet.Transmuxer/Configurations/FFmpegTransmuxerFactoryConfiguration.cs
    startLine: 32
  assemblies:
  - LiveStreamingServerNet.Transmuxer
  namespace: LiveStreamingServerNet.Transmuxer.Configurations
  syntax:
    content: public delegate Task<string> FFmpegOutputPathResolverDelegate(Guid contextIdentifier, string streamPath, IReadOnlyDictionary<string, string> streamArguments)
    parameters:
    - id: contextIdentifier
      type: System.Guid
    - id: streamPath
      type: System.String
    - id: streamArguments
      type: System.Collections.Generic.IReadOnlyDictionary{System.String,System.String}
    return:
      type: System.Threading.Tasks.Task{System.String}
    content.vb: Public Delegate Function FFmpegOutputPathResolverDelegate(contextIdentifier As Guid, streamPath As String, streamArguments As IReadOnlyDictionary(Of String, String)) As Task(Of String)
  extensionMethods:
  - System.Object.LiveStreamingServerNet.Utilities.Extensions.LockExtensions.Lock(System.Action)
references:
- uid: LiveStreamingServerNet.Transmuxer.Configurations
  commentId: N:LiveStreamingServerNet.Transmuxer.Configurations
  href: LiveStreamingServerNet.html
  name: LiveStreamingServerNet.Transmuxer.Configurations
  nameWithType: LiveStreamingServerNet.Transmuxer.Configurations
  fullName: LiveStreamingServerNet.Transmuxer.Configurations
  spec.csharp:
  - uid: LiveStreamingServerNet
    name: LiveStreamingServerNet
    href: LiveStreamingServerNet.html
  - name: .
  - uid: LiveStreamingServerNet.Transmuxer
    name: Transmuxer
    href: LiveStreamingServerNet.Transmuxer.html
  - name: .
  - uid: LiveStreamingServerNet.Transmuxer.Configurations
    name: Configurations
    href: LiveStreamingServerNet.Transmuxer.Configurations.html
  spec.vb:
  - uid: LiveStreamingServerNet
    name: LiveStreamingServerNet
    href: LiveStreamingServerNet.html
  - name: .
  - uid: LiveStreamingServerNet.Transmuxer
    name: Transmuxer
    href: LiveStreamingServerNet.Transmuxer.html
  - name: .
  - uid: LiveStreamingServerNet.Transmuxer.Configurations
    name: Configurations
    href: LiveStreamingServerNet.Transmuxer.Configurations.html
- uid: System.Object.LiveStreamingServerNet.Utilities.Extensions.LockExtensions.Lock(System.Action)
  commentId: M:LiveStreamingServerNet.Utilities.Extensions.LockExtensions.Lock(System.Object,System.Action)
  parent: LiveStreamingServerNet.Utilities.Extensions.LockExtensions
  definition: LiveStreamingServerNet.Utilities.Extensions.LockExtensions.Lock(System.Object,System.Action)
  href: LiveStreamingServerNet.Utilities.Extensions.LockExtensions.html#LiveStreamingServerNet_Utilities_Extensions_LockExtensions_Lock_System_Object_System_Action_
  name: Lock(object, Action)
  nameWithType: LockExtensions.Lock(object, Action)
  fullName: LiveStreamingServerNet.Utilities.Extensions.LockExtensions.Lock(object, System.Action)
  nameWithType.vb: LockExtensions.Lock(Object, Action)
  fullName.vb: LiveStreamingServerNet.Utilities.Extensions.LockExtensions.Lock(Object, System.Action)
  name.vb: Lock(Object, Action)
  spec.csharp:
  - uid: LiveStreamingServerNet.Utilities.Extensions.LockExtensions.Lock(System.Object,System.Action)
    name: Lock
    href: LiveStreamingServerNet.Utilities.Extensions.LockExtensions.html#LiveStreamingServerNet_Utilities_Extensions_LockExtensions_Lock_System_Object_System_Action_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Action
    name: Action
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.action
  - name: )
  spec.vb:
  - uid: LiveStreamingServerNet.Utilities.Extensions.LockExtensions.Lock(System.Object,System.Action)
    name: Lock
    href: LiveStreamingServerNet.Utilities.Extensions.LockExtensions.html#LiveStreamingServerNet_Utilities_Extensions_LockExtensions_Lock_System_Object_System_Action_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Action
    name: Action
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.action
  - name: )
- uid: System.Guid
  commentId: T:System.Guid
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.guid
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System.Collections.Generic.IReadOnlyDictionary{System.String,System.String}
  commentId: T:System.Collections.Generic.IReadOnlyDictionary{System.String,System.String}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IReadOnlyDictionary`2
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlydictionary-2
  name: IReadOnlyDictionary<string, string>
  nameWithType: IReadOnlyDictionary<string, string>
  fullName: System.Collections.Generic.IReadOnlyDictionary<string, string>
  nameWithType.vb: IReadOnlyDictionary(Of String, String)
  fullName.vb: System.Collections.Generic.IReadOnlyDictionary(Of String, String)
  name.vb: IReadOnlyDictionary(Of String, String)
  spec.csharp:
  - uid: System.Collections.Generic.IReadOnlyDictionary`2
    name: IReadOnlyDictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlydictionary-2
  - name: <
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.IReadOnlyDictionary`2
    name: IReadOnlyDictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlydictionary-2
  - name: (
  - name: Of
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: ','
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: )
- uid: System.Threading.Tasks.Task{System.String}
  commentId: T:System.Threading.Tasks.Task{System.String}
  parent: System.Threading.Tasks
  definition: System.Threading.Tasks.Task`1
  href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  name: Task<string>
  nameWithType: Task<string>
  fullName: System.Threading.Tasks.Task<string>
  nameWithType.vb: Task(Of String)
  fullName.vb: System.Threading.Tasks.Task(Of String)
  name.vb: Task(Of String)
  spec.csharp:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: <
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: '>'
  spec.vb:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: (
  - name: Of
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: )
- uid: LiveStreamingServerNet.Utilities.Extensions.LockExtensions.Lock(System.Object,System.Action)
  commentId: M:LiveStreamingServerNet.Utilities.Extensions.LockExtensions.Lock(System.Object,System.Action)
  isExternal: true
  href: LiveStreamingServerNet.Utilities.Extensions.LockExtensions.html#LiveStreamingServerNet_Utilities_Extensions_LockExtensions_Lock_System_Object_System_Action_
  name: Lock(object, Action)
  nameWithType: LockExtensions.Lock(object, Action)
  fullName: LiveStreamingServerNet.Utilities.Extensions.LockExtensions.Lock(object, System.Action)
  nameWithType.vb: LockExtensions.Lock(Object, Action)
  fullName.vb: LiveStreamingServerNet.Utilities.Extensions.LockExtensions.Lock(Object, System.Action)
  name.vb: Lock(Object, Action)
  spec.csharp:
  - uid: LiveStreamingServerNet.Utilities.Extensions.LockExtensions.Lock(System.Object,System.Action)
    name: Lock
    href: LiveStreamingServerNet.Utilities.Extensions.LockExtensions.html#LiveStreamingServerNet_Utilities_Extensions_LockExtensions_Lock_System_Object_System_Action_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Action
    name: Action
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.action
  - name: )
  spec.vb:
  - uid: LiveStreamingServerNet.Utilities.Extensions.LockExtensions.Lock(System.Object,System.Action)
    name: Lock
    href: LiveStreamingServerNet.Utilities.Extensions.LockExtensions.html#LiveStreamingServerNet_Utilities_Extensions_LockExtensions_Lock_System_Object_System_Action_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Action
    name: Action
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.action
  - name: )
- uid: LiveStreamingServerNet.Utilities.Extensions.LockExtensions
  commentId: T:LiveStreamingServerNet.Utilities.Extensions.LockExtensions
  parent: LiveStreamingServerNet.Utilities.Extensions
  href: LiveStreamingServerNet.Utilities.Extensions.LockExtensions.html
  name: LockExtensions
  nameWithType: LockExtensions
  fullName: LiveStreamingServerNet.Utilities.Extensions.LockExtensions
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.Collections.Generic.IReadOnlyDictionary`2
  commentId: T:System.Collections.Generic.IReadOnlyDictionary`2
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlydictionary-2
  name: IReadOnlyDictionary<TKey, TValue>
  nameWithType: IReadOnlyDictionary<TKey, TValue>
  fullName: System.Collections.Generic.IReadOnlyDictionary<TKey, TValue>
  nameWithType.vb: IReadOnlyDictionary(Of TKey, TValue)
  fullName.vb: System.Collections.Generic.IReadOnlyDictionary(Of TKey, TValue)
  name.vb: IReadOnlyDictionary(Of TKey, TValue)
  spec.csharp:
  - uid: System.Collections.Generic.IReadOnlyDictionary`2
    name: IReadOnlyDictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlydictionary-2
  - name: <
  - name: TKey
  - name: ','
  - name: " "
  - name: TValue
  - name: '>'
  spec.vb:
  - uid: System.Collections.Generic.IReadOnlyDictionary`2
    name: IReadOnlyDictionary
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.ireadonlydictionary-2
  - name: (
  - name: Of
  - name: " "
  - name: TKey
  - name: ','
  - name: " "
  - name: TValue
  - name: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Generic
    name: Generic
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic
- uid: System.Threading.Tasks.Task`1
  commentId: T:System.Threading.Tasks.Task`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  name: Task<TResult>
  nameWithType: Task<TResult>
  fullName: System.Threading.Tasks.Task<TResult>
  nameWithType.vb: Task(Of TResult)
  fullName.vb: System.Threading.Tasks.Task(Of TResult)
  name.vb: Task(Of TResult)
  spec.csharp:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: <
  - name: TResult
  - name: '>'
  spec.vb:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: (
  - name: Of
  - name: " "
  - name: TResult
  - name: )
- uid: System.Threading.Tasks
  commentId: N:System.Threading.Tasks
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Threading.Tasks
  nameWithType: System.Threading.Tasks
  fullName: System.Threading.Tasks
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks
- uid: LiveStreamingServerNet.Utilities.Extensions
  commentId: N:LiveStreamingServerNet.Utilities.Extensions
  href: LiveStreamingServerNet.html
  name: LiveStreamingServerNet.Utilities.Extensions
  nameWithType: LiveStreamingServerNet.Utilities.Extensions
  fullName: LiveStreamingServerNet.Utilities.Extensions
  spec.csharp:
  - uid: LiveStreamingServerNet
    name: LiveStreamingServerNet
    href: LiveStreamingServerNet.html
  - name: .
  - uid: LiveStreamingServerNet.Utilities
    name: Utilities
    href: LiveStreamingServerNet.Utilities.html
  - name: .
  - uid: LiveStreamingServerNet.Utilities.Extensions
    name: Extensions
    href: LiveStreamingServerNet.Utilities.Extensions.html
  spec.vb:
  - uid: LiveStreamingServerNet
    name: LiveStreamingServerNet
    href: LiveStreamingServerNet.html
  - name: .
  - uid: LiveStreamingServerNet.Utilities
    name: Utilities
    href: LiveStreamingServerNet.Utilities.html
  - name: .
  - uid: LiveStreamingServerNet.Utilities.Extensions
    name: Extensions
    href: LiveStreamingServerNet.Utilities.Extensions.html
