### YamlMime:ManagedReference
items:
- uid: LiveStreamingServerNet.KubernetesPod.Configurations
  commentId: N:LiveStreamingServerNet.KubernetesPod.Configurations
  id: LiveStreamingServerNet.KubernetesPod.Configurations
  children:
  - LiveStreamingServerNet.KubernetesPod.Configurations.KubernetesPodConfiguration
  - LiveStreamingServerNet.KubernetesPod.Configurations.StreamRegistryConfiguration
  langs:
  - csharp
  - vb
  name: LiveStreamingServerNet.KubernetesPod.Configurations
  nameWithType: LiveStreamingServerNet.KubernetesPod.Configurations
  fullName: LiveStreamingServerNet.KubernetesPod.Configurations
  type: Namespace
  assemblies:
  - LiveStreamingServerNet.KubernetesPod
references:
- uid: LiveStreamingServerNet.KubernetesPod.Configurations.KubernetesPodConfiguration
  commentId: T:LiveStreamingServerNet.KubernetesPod.Configurations.KubernetesPodConfiguration
  href: LiveStreamingServerNet.KubernetesPod.Configurations.KubernetesPodConfiguration.html
  name: KubernetesPodConfiguration
  nameWithType: KubernetesPodConfiguration
  fullName: LiveStreamingServerNet.KubernetesPod.Configurations.KubernetesPodConfiguration
- uid: LiveStreamingServerNet.KubernetesPod.Configurations.StreamRegistryConfiguration
  commentId: T:LiveStreamingServerNet.KubernetesPod.Configurations.StreamRegistryConfiguration
  href: LiveStreamingServerNet.KubernetesPod.Configurations.StreamRegistryConfiguration.html
  name: StreamRegistryConfiguration
  nameWithType: StreamRegistryConfiguration
  fullName: LiveStreamingServerNet.KubernetesPod.Configurations.StreamRegistryConfiguration
