### YamlMime:ManagedReference
items:
- uid: LiveStreamingServerNet.Networking.Configurations
  commentId: N:LiveStreamingServerNet.Networking.Configurations
  id: LiveStreamingServerNet.Networking.Configurations
  children:
  - LiveStreamingServerNet.Networking.Configurations.NetBufferPoolConfiguration
  - LiveStreamingServerNet.Networking.Configurations.SecurityConfiguration
  langs:
  - csharp
  - vb
  name: LiveStreamingServerNet.Networking.Configurations
  nameWithType: LiveStreamingServerNet.Networking.Configurations
  fullName: LiveStreamingServerNet.Networking.Configurations
  type: Namespace
  assemblies:
  - LiveStreamingServerNet.Networking
references:
- uid: LiveStreamingServerNet.Networking.Configurations.NetBufferPoolConfiguration
  commentId: T:LiveStreamingServerNet.Networking.Configurations.NetBufferPoolConfiguration
  href: LiveStreamingServerNet.Networking.Configurations.NetBufferPoolConfiguration.html
  name: NetBufferPoolConfiguration
  nameWithType: NetBufferPoolConfiguration
  fullName: LiveStreamingServerNet.Networking.Configurations.NetBufferPoolConfiguration
- uid: LiveStreamingServerNet.Networking.Configurations.SecurityConfiguration
  commentId: T:LiveStreamingServerNet.Networking.Configurations.SecurityConfiguration
  href: LiveStreamingServerNet.Networking.Configurations.SecurityConfiguration.html
  name: SecurityConfiguration
  nameWithType: SecurityConfiguration
  fullName: LiveStreamingServerNet.Networking.Configurations.SecurityConfiguration
