### YamlMime:ManagedReference
items:
- uid: LiveStreamingServerNet.KubernetesPod.Redis.Configurations
  commentId: N:LiveStreamingServerNet.KubernetesPod.Redis.Configurations
  id: LiveStreamingServerNet.KubernetesPod.Redis.Configurations
  children:
  - LiveStreamingServerNet.KubernetesPod.Redis.Configurations.RedisStoreConfiguration
  langs:
  - csharp
  - vb
  name: LiveStreamingServerNet.KubernetesPod.Redis.Configurations
  nameWithType: LiveStreamingServerNet.KubernetesPod.Redis.Configurations
  fullName: LiveStreamingServerNet.KubernetesPod.Redis.Configurations
  type: Namespace
  assemblies:
  - LiveStreamingServerNet.KubernetesPod.Redis
references:
- uid: LiveStreamingServerNet.KubernetesPod.Redis.Configurations.RedisStoreConfiguration
  commentId: T:LiveStreamingServerNet.KubernetesPod.Redis.Configurations.RedisStoreConfiguration
  href: LiveStreamingServerNet.KubernetesPod.Redis.Configurations.RedisStoreConfiguration.html
  name: RedisStoreConfiguration
  nameWithType: RedisStoreConfiguration
  fullName: LiveStreamingServerNet.KubernetesPod.Redis.Configurations.RedisStoreConfiguration
