### YamlMime:ManagedReference
items:
- uid: LiveStreamingServerNet.Flv.Installer.Contracts.IFlvConfigurator
  commentId: T:LiveStreamingServerNet.Flv.Installer.Contracts.IFlvConfigurator
  id: IFlvConfigurator
  parent: LiveStreamingServerNet.Flv.Installer.Contracts
  children:
  - LiveStreamingServerNet.Flv.Installer.Contracts.IFlvConfigurator.ConfigureMediaMessage(System.Action{LiveStreamingServerNet.Flv.Configurations.MediaMessageConfiguration})
  langs:
  - csharp
  - vb
  name: IFlvConfigurator
  nameWithType: IFlvConfigurator
  fullName: LiveStreamingServerNet.Flv.Installer.Contracts.IFlvConfigurator
  type: Interface
  source:
    remote:
      path: src/LiveStreamingServerNet.Flv/Installer/Contracts/IFlvConfigurator.cs
      branch: features/docs
      repo: https://josephnhtam@github.com/josephnhtam/live-streaming-server-net.git
    id: IFlvConfigurator
    path: ../src/LiveStreamingServerNet.Flv/Installer/Contracts/IFlvConfigurator.cs
    startLine: 4
  assemblies:
  - LiveStreamingServerNet.Flv
  namespace: LiveStreamingServerNet.Flv.Installer.Contracts
  syntax:
    content: public interface IFlvConfigurator
    content.vb: Public Interface IFlvConfigurator
  extensionMethods:
  - System.Object.LiveStreamingServerNet.Utilities.Extensions.LockExtensions.Lock(System.Action)
- uid: LiveStreamingServerNet.Flv.Installer.Contracts.IFlvConfigurator.ConfigureMediaMessage(System.Action{LiveStreamingServerNet.Flv.Configurations.MediaMessageConfiguration})
  commentId: M:LiveStreamingServerNet.Flv.Installer.Contracts.IFlvConfigurator.ConfigureMediaMessage(System.Action{LiveStreamingServerNet.Flv.Configurations.MediaMessageConfiguration})
  id: ConfigureMediaMessage(System.Action{LiveStreamingServerNet.Flv.Configurations.MediaMessageConfiguration})
  parent: LiveStreamingServerNet.Flv.Installer.Contracts.IFlvConfigurator
  langs:
  - csharp
  - vb
  name: ConfigureMediaMessage(Action<MediaMessageConfiguration>?)
  nameWithType: IFlvConfigurator.ConfigureMediaMessage(Action<MediaMessageConfiguration>?)
  fullName: LiveStreamingServerNet.Flv.Installer.Contracts.IFlvConfigurator.ConfigureMediaMessage(System.Action<LiveStreamingServerNet.Flv.Configurations.MediaMessageConfiguration>?)
  type: Method
  source:
    remote:
      path: src/LiveStreamingServerNet.Flv/Installer/Contracts/IFlvConfigurator.cs
      branch: features/docs
      repo: https://josephnhtam@github.com/josephnhtam/live-streaming-server-net.git
    id: ConfigureMediaMessage
    path: ../src/LiveStreamingServerNet.Flv/Installer/Contracts/IFlvConfigurator.cs
    startLine: 6
  assemblies:
  - LiveStreamingServerNet.Flv
  namespace: LiveStreamingServerNet.Flv.Installer.Contracts
  syntax:
    content: IFlvConfigurator ConfigureMediaMessage(Action<MediaMessageConfiguration>? configure)
    parameters:
    - id: configure
      type: System.Action{LiveStreamingServerNet.Flv.Configurations.MediaMessageConfiguration}
    return:
      type: LiveStreamingServerNet.Flv.Installer.Contracts.IFlvConfigurator
    content.vb: Function ConfigureMediaMessage(configure As Action(Of MediaMessageConfiguration)) As IFlvConfigurator
  overload: LiveStreamingServerNet.Flv.Installer.Contracts.IFlvConfigurator.ConfigureMediaMessage*
  nameWithType.vb: IFlvConfigurator.ConfigureMediaMessage(Action(Of MediaMessageConfiguration))
  fullName.vb: LiveStreamingServerNet.Flv.Installer.Contracts.IFlvConfigurator.ConfigureMediaMessage(System.Action(Of LiveStreamingServerNet.Flv.Configurations.MediaMessageConfiguration))
  name.vb: ConfigureMediaMessage(Action(Of MediaMessageConfiguration))
references:
- uid: LiveStreamingServerNet.Flv.Installer.Contracts
  commentId: N:LiveStreamingServerNet.Flv.Installer.Contracts
  href: LiveStreamingServerNet.html
  name: LiveStreamingServerNet.Flv.Installer.Contracts
  nameWithType: LiveStreamingServerNet.Flv.Installer.Contracts
  fullName: LiveStreamingServerNet.Flv.Installer.Contracts
  spec.csharp:
  - uid: LiveStreamingServerNet
    name: LiveStreamingServerNet
    href: LiveStreamingServerNet.html
  - name: .
  - uid: LiveStreamingServerNet.Flv
    name: Flv
    href: LiveStreamingServerNet.Flv.html
  - name: .
  - uid: LiveStreamingServerNet.Flv.Installer
    name: Installer
    href: LiveStreamingServerNet.Flv.Installer.html
  - name: .
  - uid: LiveStreamingServerNet.Flv.Installer.Contracts
    name: Contracts
    href: LiveStreamingServerNet.Flv.Installer.Contracts.html
  spec.vb:
  - uid: LiveStreamingServerNet
    name: LiveStreamingServerNet
    href: LiveStreamingServerNet.html
  - name: .
  - uid: LiveStreamingServerNet.Flv
    name: Flv
    href: LiveStreamingServerNet.Flv.html
  - name: .
  - uid: LiveStreamingServerNet.Flv.Installer
    name: Installer
    href: LiveStreamingServerNet.Flv.Installer.html
  - name: .
  - uid: LiveStreamingServerNet.Flv.Installer.Contracts
    name: Contracts
    href: LiveStreamingServerNet.Flv.Installer.Contracts.html
- uid: System.Object.LiveStreamingServerNet.Utilities.Extensions.LockExtensions.Lock(System.Action)
  commentId: M:LiveStreamingServerNet.Utilities.Extensions.LockExtensions.Lock(System.Object,System.Action)
  parent: LiveStreamingServerNet.Utilities.Extensions.LockExtensions
  definition: LiveStreamingServerNet.Utilities.Extensions.LockExtensions.Lock(System.Object,System.Action)
  href: LiveStreamingServerNet.Utilities.Extensions.LockExtensions.html#LiveStreamingServerNet_Utilities_Extensions_LockExtensions_Lock_System_Object_System_Action_
  name: Lock(object, Action)
  nameWithType: LockExtensions.Lock(object, Action)
  fullName: LiveStreamingServerNet.Utilities.Extensions.LockExtensions.Lock(object, System.Action)
  nameWithType.vb: LockExtensions.Lock(Object, Action)
  fullName.vb: LiveStreamingServerNet.Utilities.Extensions.LockExtensions.Lock(Object, System.Action)
  name.vb: Lock(Object, Action)
  spec.csharp:
  - uid: LiveStreamingServerNet.Utilities.Extensions.LockExtensions.Lock(System.Object,System.Action)
    name: Lock
    href: LiveStreamingServerNet.Utilities.Extensions.LockExtensions.html#LiveStreamingServerNet_Utilities_Extensions_LockExtensions_Lock_System_Object_System_Action_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Action
    name: Action
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.action
  - name: )
  spec.vb:
  - uid: LiveStreamingServerNet.Utilities.Extensions.LockExtensions.Lock(System.Object,System.Action)
    name: Lock
    href: LiveStreamingServerNet.Utilities.Extensions.LockExtensions.html#LiveStreamingServerNet_Utilities_Extensions_LockExtensions_Lock_System_Object_System_Action_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Action
    name: Action
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.action
  - name: )
- uid: LiveStreamingServerNet.Utilities.Extensions.LockExtensions.Lock(System.Object,System.Action)
  commentId: M:LiveStreamingServerNet.Utilities.Extensions.LockExtensions.Lock(System.Object,System.Action)
  isExternal: true
  href: LiveStreamingServerNet.Utilities.Extensions.LockExtensions.html#LiveStreamingServerNet_Utilities_Extensions_LockExtensions_Lock_System_Object_System_Action_
  name: Lock(object, Action)
  nameWithType: LockExtensions.Lock(object, Action)
  fullName: LiveStreamingServerNet.Utilities.Extensions.LockExtensions.Lock(object, System.Action)
  nameWithType.vb: LockExtensions.Lock(Object, Action)
  fullName.vb: LiveStreamingServerNet.Utilities.Extensions.LockExtensions.Lock(Object, System.Action)
  name.vb: Lock(Object, Action)
  spec.csharp:
  - uid: LiveStreamingServerNet.Utilities.Extensions.LockExtensions.Lock(System.Object,System.Action)
    name: Lock
    href: LiveStreamingServerNet.Utilities.Extensions.LockExtensions.html#LiveStreamingServerNet_Utilities_Extensions_LockExtensions_Lock_System_Object_System_Action_
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Action
    name: Action
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.action
  - name: )
  spec.vb:
  - uid: LiveStreamingServerNet.Utilities.Extensions.LockExtensions.Lock(System.Object,System.Action)
    name: Lock
    href: LiveStreamingServerNet.Utilities.Extensions.LockExtensions.html#LiveStreamingServerNet_Utilities_Extensions_LockExtensions_Lock_System_Object_System_Action_
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Action
    name: Action
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.action
  - name: )
- uid: LiveStreamingServerNet.Utilities.Extensions.LockExtensions
  commentId: T:LiveStreamingServerNet.Utilities.Extensions.LockExtensions
  parent: LiveStreamingServerNet.Utilities.Extensions
  href: LiveStreamingServerNet.Utilities.Extensions.LockExtensions.html
  name: LockExtensions
  nameWithType: LockExtensions
  fullName: LiveStreamingServerNet.Utilities.Extensions.LockExtensions
- uid: LiveStreamingServerNet.Utilities.Extensions
  commentId: N:LiveStreamingServerNet.Utilities.Extensions
  href: LiveStreamingServerNet.html
  name: LiveStreamingServerNet.Utilities.Extensions
  nameWithType: LiveStreamingServerNet.Utilities.Extensions
  fullName: LiveStreamingServerNet.Utilities.Extensions
  spec.csharp:
  - uid: LiveStreamingServerNet
    name: LiveStreamingServerNet
    href: LiveStreamingServerNet.html
  - name: .
  - uid: LiveStreamingServerNet.Utilities
    name: Utilities
    href: LiveStreamingServerNet.Utilities.html
  - name: .
  - uid: LiveStreamingServerNet.Utilities.Extensions
    name: Extensions
    href: LiveStreamingServerNet.Utilities.Extensions.html
  spec.vb:
  - uid: LiveStreamingServerNet
    name: LiveStreamingServerNet
    href: LiveStreamingServerNet.html
  - name: .
  - uid: LiveStreamingServerNet.Utilities
    name: Utilities
    href: LiveStreamingServerNet.Utilities.html
  - name: .
  - uid: LiveStreamingServerNet.Utilities.Extensions
    name: Extensions
    href: LiveStreamingServerNet.Utilities.Extensions.html
- uid: LiveStreamingServerNet.Flv.Installer.Contracts.IFlvConfigurator.ConfigureMediaMessage*
  commentId: Overload:LiveStreamingServerNet.Flv.Installer.Contracts.IFlvConfigurator.ConfigureMediaMessage
  href: LiveStreamingServerNet.Flv.Installer.Contracts.IFlvConfigurator.html#LiveStreamingServerNet_Flv_Installer_Contracts_IFlvConfigurator_ConfigureMediaMessage_System_Action_LiveStreamingServerNet_Flv_Configurations_MediaMessageConfiguration__
  name: ConfigureMediaMessage
  nameWithType: IFlvConfigurator.ConfigureMediaMessage
  fullName: LiveStreamingServerNet.Flv.Installer.Contracts.IFlvConfigurator.ConfigureMediaMessage
- uid: System.Action{LiveStreamingServerNet.Flv.Configurations.MediaMessageConfiguration}
  commentId: T:System.Action{LiveStreamingServerNet.Flv.Configurations.MediaMessageConfiguration}
  parent: System
  definition: System.Action`1
  href: https://learn.microsoft.com/dotnet/api/system.action-1
  name: Action<MediaMessageConfiguration>
  nameWithType: Action<MediaMessageConfiguration>
  fullName: System.Action<LiveStreamingServerNet.Flv.Configurations.MediaMessageConfiguration>
  nameWithType.vb: Action(Of MediaMessageConfiguration)
  fullName.vb: System.Action(Of LiveStreamingServerNet.Flv.Configurations.MediaMessageConfiguration)
  name.vb: Action(Of MediaMessageConfiguration)
  spec.csharp:
  - uid: System.Action`1
    name: Action
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.action-1
  - name: <
  - uid: LiveStreamingServerNet.Flv.Configurations.MediaMessageConfiguration
    name: MediaMessageConfiguration
    href: LiveStreamingServerNet.Flv.Configurations.MediaMessageConfiguration.html
  - name: '>'
  spec.vb:
  - uid: System.Action`1
    name: Action
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.action-1
  - name: (
  - name: Of
  - name: " "
  - uid: LiveStreamingServerNet.Flv.Configurations.MediaMessageConfiguration
    name: MediaMessageConfiguration
    href: LiveStreamingServerNet.Flv.Configurations.MediaMessageConfiguration.html
  - name: )
- uid: LiveStreamingServerNet.Flv.Installer.Contracts.IFlvConfigurator
  commentId: T:LiveStreamingServerNet.Flv.Installer.Contracts.IFlvConfigurator
  parent: LiveStreamingServerNet.Flv.Installer.Contracts
  href: LiveStreamingServerNet.Flv.Installer.Contracts.IFlvConfigurator.html
  name: IFlvConfigurator
  nameWithType: IFlvConfigurator
  fullName: LiveStreamingServerNet.Flv.Installer.Contracts.IFlvConfigurator
- uid: System.Action`1
  commentId: T:System.Action`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.action-1
  name: Action<T>
  nameWithType: Action<T>
  fullName: System.Action<T>
  nameWithType.vb: Action(Of T)
  fullName.vb: System.Action(Of T)
  name.vb: Action(Of T)
  spec.csharp:
  - uid: System.Action`1
    name: Action
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.action-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Action`1
    name: Action
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.action-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
