### YamlMime:ManagedReference
items:
- uid: LiveStreamingServerNet.Transmuxer.Configurations
  commentId: N:LiveStreamingServerNet.Transmuxer.Configurations
  id: LiveStreamingServerNet.Transmuxer.Configurations
  children:
  - LiveStreamingServerNet.Transmuxer.Configurations.FFmpegOutputPathResolverDelegate
  - LiveStreamingServerNet.Transmuxer.Configurations.FFmpegTransmuxerFactoryConfiguration
  - LiveStreamingServerNet.Transmuxer.Configurations.HlsUploaderConfiguration
  langs:
  - csharp
  - vb
  name: LiveStreamingServerNet.Transmuxer.Configurations
  nameWithType: LiveStreamingServerNet.Transmuxer.Configurations
  fullName: LiveStreamingServerNet.Transmuxer.Configurations
  type: Namespace
  assemblies:
  - LiveStreamingServerNet.Transmuxer
references:
- uid: LiveStreamingServerNet.Transmuxer.Configurations.FFmpegTransmuxerFactoryConfiguration
  commentId: T:LiveStreamingServerNet.Transmuxer.Configurations.FFmpegTransmuxerFactoryConfiguration
  parent: LiveStreamingServerNet.Transmuxer.Configurations
  href: LiveStreamingServerNet.Transmuxer.Configurations.FFmpegTransmuxerFactoryConfiguration.html
  name: FFmpegTransmuxerFactoryConfiguration
  nameWithType: FFmpegTransmuxerFactoryConfiguration
  fullName: LiveStreamingServerNet.Transmuxer.Configurations.FFmpegTransmuxerFactoryConfiguration
- uid: LiveStreamingServerNet.Transmuxer.Configurations.FFmpegOutputPathResolverDelegate
  commentId: T:LiveStreamingServerNet.Transmuxer.Configurations.FFmpegOutputPathResolverDelegate
  parent: LiveStreamingServerNet.Transmuxer.Configurations
  href: LiveStreamingServerNet.Transmuxer.Configurations.FFmpegOutputPathResolverDelegate.html
  name: FFmpegOutputPathResolverDelegate
  nameWithType: FFmpegOutputPathResolverDelegate
  fullName: LiveStreamingServerNet.Transmuxer.Configurations.FFmpegOutputPathResolverDelegate
- uid: LiveStreamingServerNet.Transmuxer.Configurations.HlsUploaderConfiguration
  commentId: T:LiveStreamingServerNet.Transmuxer.Configurations.HlsUploaderConfiguration
  href: LiveStreamingServerNet.Transmuxer.Configurations.HlsUploaderConfiguration.html
  name: HlsUploaderConfiguration
  nameWithType: HlsUploaderConfiguration
  fullName: LiveStreamingServerNet.Transmuxer.Configurations.HlsUploaderConfiguration
- uid: LiveStreamingServerNet.Transmuxer.Configurations
  commentId: N:LiveStreamingServerNet.Transmuxer.Configurations
  href: LiveStreamingServerNet.html
  name: LiveStreamingServerNet.Transmuxer.Configurations
  nameWithType: LiveStreamingServerNet.Transmuxer.Configurations
  fullName: LiveStreamingServerNet.Transmuxer.Configurations
  spec.csharp:
  - uid: LiveStreamingServerNet
    name: LiveStreamingServerNet
    href: LiveStreamingServerNet.html
  - name: .
  - uid: LiveStreamingServerNet.Transmuxer
    name: Transmuxer
    href: LiveStreamingServerNet.Transmuxer.html
  - name: .
  - uid: LiveStreamingServerNet.Transmuxer.Configurations
    name: Configurations
    href: LiveStreamingServerNet.Transmuxer.Configurations.html
  spec.vb:
  - uid: LiveStreamingServerNet
    name: LiveStreamingServerNet
    href: LiveStreamingServerNet.html
  - name: .
  - uid: LiveStreamingServerNet.Transmuxer
    name: Transmuxer
    href: LiveStreamingServerNet.Transmuxer.html
  - name: .
  - uid: LiveStreamingServerNet.Transmuxer.Configurations
    name: Configurations
    href: LiveStreamingServerNet.Transmuxer.Configurations.html
